[tool.poetry]
name = "context_logging"
version = "1.0.0"
description = "Tool for easy logging with current context information"
authors = ["Evgeniy Afonasev <ea.afonasev@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/Afonasev/context_logging"
homepage = "https://pypi.org/project/context_logging"
keywords = []

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0",allows-prereleases = true}
bumpversion = "^0.6.0"
flake8-awesome = "^1.2"
mypy = "^0.770"
pylint = "^2.2"
pytest = "^5.4"
pytest-cov = "^2.9"
pytest-deadfixtures = "^2.2"
pytest-mock = "^3.1"
unify = "^0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
